apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hookshot.fullname" . }}-passkey
  labels:
    {{- include "hookshot.labels" . | nindent 4 }}
type: Opaque
data:
  passkey.pem: {{ .Values.passkey | b64enc | quote }}
