replicaCount: 1

image:
  repository: glanceapp/glance
  pullPolicy: IfNotPresent
  tag: "v0.6.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: "selfsign-clusterissuer"
  hosts:
    - host: glance.home
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: glance-server-tls
      hosts:
        - glance.home


livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http


glance:
  config:
    theme:
      background-color: 240 3 12
      primary-color: 180 100 27
      contrast-multiplier: 1.1
    pages:
      - name: Home
        columns:
          - size: small
            widgets:
              - type: calendar

              - type: rss
                limit: 10
                collapse-after: 3
                cache: 3h
                feeds:
                  - url: https://ciechanow.ski/atom.xml
                  - url: https://www.joshwcomeau.com/rss.xml
                    title: Josh Comeau
                  - url: https://samwho.dev/rss.xml
                  - url: https://awesomekling.github.io/feed.xml
                  - url: https://ishadeed.com/feed.xml
                    title: Ahmad Shadeed

              - type: twitch-channels
                channels:
                  - theprimeagen
                  - cohhcarnage
                  - christitustech
                  - blurbs
                  - asmongold
                  - jembawls

          - size: full
            widgets:
              - type: hacker-news

              - type: videos
                channels:
                  - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
                  - UCv6J_jJa8GJqFwQNgNrMuww # ServeTheHome
                  - UCOk-gHyjcWZNj3Br4oxwh0A # Techno Tim

              - type: reddit
                subreddit: selfhosted

          - size: small
            widgets:
              - type: weather
                location: London, United Kingdom

              - type: markets
                markets:
                  - symbol: SPY
                    name: S&P 500
                  - symbol: BTC-USD
                    name: Bitcoin
                  - symbol: NVDA
                    name: NVIDIA
                  - symbol: AAPL
                    name: Apple
                  - symbol: MSFT
                    name: Microsoft
                  - symbol: GOOGL
                    name: Google
                  - symbol: AMD
                    name: AMD
                  - symbol: RDDT
                    name: Reddit
