apiVersion: v2
name: kadalu
icon: https://kadalu.io/static/css/logo.png
description: Contains chart for deploying Kadalu Operator
type: application
version: 1.3.0
dependencies:
  - name: common
    version: ">=0.0.0-0"
    repository: file://charts/common
  - name: operator
    version: ">=0.0.0-0"
    repository: file://charts/operator
    condition: operator.enabled
